### ISSUE TITLE
Coordinate Conversion - Increase number of decimal places for DD and DDM

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-conversion-addin-dotnet#162]
_From @elinz on November 4, 2016 22:33_

For DD and DDM options in the "Add New Output Coordinate" we should increase the number of decimal places, we only display out to a single decimal place. This is approximately 6-7 nautical miles, which is too course and we should display out to two places. Especially since the map display units will display out to two decimal places.

![image](https://cloud.githubusercontent.com/assets/4635490/20024380/7891045a-a2a3-11e6-84a5-a51f0376efb7.png)

And update the Sample coordinate shown in the "Add New Output Coordinate" to match.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

_Copied from original issue: Esri/military-tools-for-arcgis#61_

**Comment by lfunkhouser** [comment]
_From @jmccausland on November 8, 2016 20:57_

The "Input" group currently has no UI to configure it's format.  If you do not use "Edit Properties" the input format defaults to {0.0}.  Don't confuse the output format options with the input.

**Comment by lfunkhouser** [comment]
_From @nfeuerstein on December 2, 2016 16:40_

@jmccausland and @elinz can this issue be closed out?  Can the user use "edit properties" to set the decimal places?

**Comment by lfunkhouser** [comment]
_From @jmccausland on December 2, 2016 16:49_

There are no configuration properties to format the input decimal places.  Currently you can only change the type of coordinate.

**Comment by elinz** [comment]
@nfeuerstein @jmccausland I'm going to close this issue. The way I wrote this issue is very confusing. I'm mixing up the input and output coordinate formats. As @jmccausland stated there is no interface for configuring the input format, and there shouldn't be as you would want the user to input whatever coordinate format with whatever number of decimal places.

I created the issues #157 and #158 regarding the number of decimal places in the output formats issue.
