### ISSUE TITLE
WGS 1984 explanation in the intro topic for Coordinate Conversion

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#213]
In the intro topic for coordinate conversion it is stated that you need to be working in WGS 1984, do we need to explain this further to clarify what the problem is, and what will happen if you are not

**Comment by jmhauck** [comment]
When using display coordinate type of DD and the MapTool.
 - all input coordinates are assumed to be WGS_84...there is a Project call that will project incoming coordinates to WGS_84.

When using display coordinate type of Default Map Unit and the MapTool
 - Project is not called. It is assumed that the incoming coordinate is in the maps spatial reference.

When manually entering a coordinate.
 - all input coordinates are assumed to be in WGS 84 unless they are projected coordinate values (more than 3 numbers before the decimal or coordinate pair separator) then they are assumed to be in the spatial reference of the map.
 - Prior to the fix for #153 all projected coordinate values were assumed to be in WebMercator rather than the maps spatial reference.

**Comment by topowright** [comment]
This has been done.
