### ISSUE TITLE
Doc-Coordinate Conversion: "Customize a coordinate format" does not include instructions on how to format DD/DDM/DMS (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#232]
For DD, DDM, and DMS formats, the user can customize the output, however, we don't have any content in this .pdf topic to explain how users can do this.

For example, using # and 0's to format decimal places.
![image](https://cloud.githubusercontent.com/assets/4635490/21785166/4928a160-d673-11e6-89a0-9cf55d279064.png)

**Comment by elinz** [comment]
Should also include content on how to customize the output of the other coordinate systems also.

**Comment by Dbarnes1** [comment]
see comment in: https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/231

**Comment by elinz** [comment]
@Dbarnes1 @nfeuerstein Sounds good.

**Comment by dfoll** [comment]
@topowright could you review the published documentation and see if you feel this is sufficiently documented now, if so please remove the "affects documentation" tag, if not we need to address this

**Comment by dfoll** [comment]
closing. @topowright @lfunkhouser @NatalieCampos reviewed what exists in the documentation in the "customize coordinate" section. we came to consensus that the "affects documentation" aspect of this is taken care of. because the issue was just documentation based, closing because the documentation has been updated sufficiently
