### ISSUE TITLE
MGRS doesn't match USNG value for same DD coordinate (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#273]
MGRS and USNG values should match. ArcMap and the Widget are creating correct output where MGRS and USNG values that match. NOTE: the MGRS/USNG values that ArcMap and the widget are creating match what the ArcMap Identify tool creates.

I went back and tested previous builds to determine when the problem started and the issue started after the build 12 Jan 11:18

![image](https://cloud.githubusercontent.com/assets/4635490/21959667/7c2badce-da82-11e6-9ea6-ed11c191cfd3.png)

The MGRS values should match the USNG values (i.e. the USNG value is the correct values for both MGRS and USNG at the specified DD value).

Entering DD: 45.0N 100.0W produces output:
MGRS: 14TMQ2118483436
USNG: 14TMQ2118583437

Entering DD: 45.0N 100.0E produces output:
MGRS: 47TNK7881583436
USNG: 47TNK7881583437

Entering DD: 45.0S 100.0W produces output:
MGRS: 14GMR2118416563
USNG: 14GMR2118516563

Entering DD: 45.0S 100.0E produces output:
MGRS: 47GNL7881516563
USNG: 47GNL7881516563
(In this case the MGRS and USNG values match)

**Comment by elinz** [comment]
Here is some additional info I collected:

![image](https://cloud.githubusercontent.com/assets/4635490/21959741/0069a764-da86-11e6-811d-1374dbb35588.png)

Coordinates in red are those that don't match the output from the ArcMap Identify, which is the baseline. The coordinates in greee are those that match the output from ArcMap. According to @kgonzago the output coordinates from the addins should match ArcMap.
![image](https://cloud.githubusercontent.com/assets/4635490/21959746/363d5c6e-da86-11e6-8c4d-55ef697a111b.png)

![image](https://cloud.githubusercontent.com/assets/4635490/21959748/4538b470-da86-11e6-8ed0-b590934c3c42.png)

![image](https://cloud.githubusercontent.com/assets/4635490/21959752/552f9c36-da86-11e6-90f1-ed5ee9fe73e9.png)

![image](https://cloud.githubusercontent.com/assets/4635490/21959757/63baf890-da86-11e6-8a32-7c747fb265b7.png)

**Comment by elinz** [comment]
@kgonzago @nfeuerstein This highlights are need to add unit tests to verify input coordinate with expected output coordinates in the various coordinate notations.

**Comment by nfeuerstein** [comment]
Notes for tomorrow:
Thanks Eric.  This is a showstopper and will need to be resolved before we can ship.

**Comment by topowright** [comment]
@dhagens you are awesome!!! This has been fixed and I have verified that the coordinates now match. @elinz I will let you close the issue.

**Comment by elinz** [comment]
@dhagens @topowright I will install latest build and test.

**Comment by elinz** [comment]
@dhagens @topowright @nfeuerstein While the MGRS and USNG coordinates do match in Pro they are not the same coordiantes as in the ArcMap addin and the widget and not what was expected. Looks like the Pro addin was modified so that the USNG coordinate would match the MGRS coordinate, instead of the other way around. The USNG being output from Pro addin before was correct.

In the screenshots below, Pro addin on left and ArcMap addin on the right.
![image](https://cloud.githubusercontent.com/assets/4635490/22033378/21c94a68-dc9d-11e6-8125-e9082d7efc39.png)

![image](https://cloud.githubusercontent.com/assets/4635490/22033446/5d7d2098-dc9d-11e6-98b8-1849dcf8453c.png)

![image](https://cloud.githubusercontent.com/assets/4635490/22033506/99ac5408-dc9d-11e6-8cc3-d4662f65c026.png)

![image](https://cloud.githubusercontent.com/assets/4635490/22033704/69015c30-dc9e-11e6-9a39-880878e55446.png)

Assigning back to @dhagens

**Comment by dhagens** [comment]
The change to MGRS previously was a fix for where the ArcGIS Pro output under the map was not matching the output we were seeing in the coordinate tool when hovering on the map.  We cannot change that back w/o reinstating that bug.  If you want the MGRS / USNG to be the same, this fix makes that work.

**Comment by dhagens** [comment]
@elinz, @topowright , @nfeuerstein, I think that this will just have to be documented.  We can't change the MGRS back because that will cause the MGRS output in our tool to be different than the output being displayed in Pro.  For most cases that I've tested, the MGRS in Pro and ArcMap are the same.  
For example (just some random locations I selected on the map):
45.015427N 099.964321W - Same MGRS in both 
47.706587N 093.563424W - Same MGRS in both
30.717900N 083.267816W - Easting and Northing are off by 1

My guess is that the coordinates being displayed in ArcMap are using rounding, whereas the coordinates being displayed in Pro are not using rounding.  If we want our output to match the output being displayed in the Addins for the given platform, we have to match the rounding being used in our code.  So we can't change the addin to use rounding in Pro and still display the same output as Pro does.

**Comment by dhagens** [comment]
I tested a coordinate using a conversion tool at www.earthpoint.us and compared it to our results:
![image](https://cloud.githubusercontent.com/assets/13664546/22037387/f3f3feda-dcc4-11e6-83d7-59c1d37b4d80.png)

Pro
![image](https://cloud.githubusercontent.com/assets/13664546/22037414/0a76c3cc-dcc5-11e6-9cf1-3bad217ceb3c.png)

ArcMap
![image](https://cloud.githubusercontent.com/assets/13664546/22037476/44fc253c-dcc5-11e6-90f8-ee009be51678.png)

As you can see, the output from ArcMap for MGRS Easting is off by 1 in ArcMap.  Again, my assumption is that ArcMap is using rounding to display the MGRS coordinates and we have to mimic that in our addin so that our MGRS ouput is not different than what is being displayed in ArcMap.

**Comment by elinz** [comment]
@nfeuerstein @topowright Thanks for the additional info @dhagens. I understand what's going on now. 

What I didn't realize was that ArcGIS Pro and ArcMap coordinate "read-out" at the bottom of the map gives you different results for a given location (i.e. 1 meter off); I'm also assuming that ArcMap map read-out is using the MGRS rounding property. In earlier builds of the Pro addin, the Coordinate Conversion addin was returning a MGRS coordinate that matched the MGRS coordinate returned from the ArcMap addin, however, this coordinate didn't match the ArcGIS Pro "read-out". Now the coordinates returned by Coordinate Conversion addins match the "read-out" of the respectively application.

For example, here is screenshot from ArcGIS Pro addin:
![image](https://cloud.githubusercontent.com/assets/4635490/22039481/64ba148a-dcb4-11e6-8f78-932a1afdce07.png)

If I type the same coordinates in the ArcMap addin: 65.182952N 102.520200W, the output MGRS is off 1 meter from what the Pro addin returns, but this coordinate matches what the ArcMap "read-out" returns.
![image](https://cloud.githubusercontent.com/assets/4635490/22039613/d61f5df6-dcb4-11e6-9986-4b09af9c294b.png)

I will close this issue because the addins are returning the same MGRS/USNG coordinate for a given location respective of the application they are running in.
