### ISSUE TITLE
Copy selected/all from list to clipboard

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#330]
A user should be able to interact with the batch list in the same way they would an excel table. They should be able to use control and shift to highlight the entries they are interested in. When they right click they should be given the  options to copy all and copy selected. This will allow the users to take these into other applications or text files.

**Comment by topowright** [comment]
Currently there is a delete and delete all option; however, there is no copy or copy all feature.

**Comment by kgonzago** [comment]
@topowright This is now available in PR #339

**Comment by ACueva** [comment]
@kgonzago Going to kick this one back.  Part of the requirements was the ability to "interact with the batch list in the same way they would an excel table."
We are still missing the ability to:

- [ ]  Select multiple items in the list using the control and shift keys.
- [ ]  Right clicking should not include the "delete all" option.(we have a clear all button at the bottom)
- [ ]  Selecting multiple items, right click wording should be  "delete selected" instead of "delete all".

**Comment by ACueva** [comment]
fyi @dfoll

**Comment by topowright** [comment]
The delete all option needs to come off the right click option.

**Comment by dfoll** [comment]
there is one thing still missing on this issue, pretty minor in my opinion
- [ ] do not need a "Delete all" in the right-click menu, there is a clear all button on the bottom (still need the delete button though


Copy functionality has been implemented, we currently have "Copy all" and "Copy" .... "Copy all" copies all coordinates from the list (this is what we want). "Copy" copies the selected values (also what I would expect)

**Comment by topowright** [comment]
Closing this issue as designed.
