### ISSUE TITLE
BUG-000099009  The Coordinate Conversion ArcMap 1.0.1 add-in fails to populate the DMS, DD, and DDM fields if the region is set to use a comma as the decimal separator.

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/coordinate-conversion-addin-dotnet#355]
<div><div>
<span><b>Salesforce ID:</b> BUG-000099009</span><br/>
<span><b>Salesforce Submitter:</b> Ciro Romero</span><br/>
<span><b>Salesforce Submit Date:</b> 8/30/2016 7:03 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Usability</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> Ensure that the region setting is configured to use a period as the decimal separator.</span><br/>
<span><b>Product:</b> ArcGIS for Defense</span><br/>
<span><b>Functional Category:</b> ArcGIS for Defense</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.3.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by NatalieCampos** [comment]
On my windows 8 machine, I am also not able to reproduce the bug.  See the graphic below with the commas highlighted.
![image](https://cloud.githubusercontent.com/assets/5116835/26472548/8742ed72-415b-11e7-9295-e1a040e19c3b.png)

@nfeuerstein since Kevin and I are both unable to reproduce the issue, it will be closed.
