### ISSUE TITLE
No feedback why coordinate in common format is invalid

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#423]
I added a coordinate of Pyonyang, NK (39.0392° N, 125.7625° E) pasted from Google search.
Got "Please Enter Valid Coordinate" error.  
This should probably be an expected input format...
![image](https://user-images.githubusercontent.com/3801392/29219399-ea0abc7a-7e85-11e7-99ed-e549c96cb008.png)
No feedback in message about what is wrong with the coordinate.
By trial and error, determined that these are also invalid:
125.7625° E, 39.0392° N
39.0392 N, 125.7625 E
Is the problem the spaces?
This one is valid:
39.0392N, 125.7625E

(ArcGIS Pro 2.0, add-in downloaded from Solutions page, version for Pro 2.0 - add-in installer 6/28/2017)

**Comment by NatalieCampos** [comment]
The coordinates ( 39.0392° N, 125.7625° E) are not valid because there is a space between the fraction of degree mark and the Lat/Long.  Removal of the space makes these valid coordinates.  See the Supported format guide.  

http://solutionsdev.arcgis.com/defense/help/coordinate-conversion/arcgis-pro/supported-notation-formats.htm

Closing issue.

**Comment by NatalieCampos** [comment]
Though upon further testing, the same format (39.0392° N, 125.7625° E) seems to be a valid format for Distance and Direction.  

@nfeuerstein @lfunkhouser should both DD and CC accept the same coordinate variation?  As is written for CC this issue is based on user error based on the supported format documentation.  Maybe this is an enhancement request.

**Comment by BobBooth** [comment]
It would make sense to accept this format if Google is handing it out by default...
![image](https://user-images.githubusercontent.com/3801392/30218089-1f1e9e3e-9486-11e7-954a-96a2fd1e7cb4.png)

Also, it would be nice if the CC tool could provide feedback on why the coordinate isn't being parsed.

**Comment by BobBooth** [comment]
![image](https://user-images.githubusercontent.com/3801392/30871519-27e8f4b4-a2b5-11e7-921a-c61c0aa941ac.png)
If we can parse space-delimited DMS, it seems strange not to be able to parse this case.
