### ISSUE TITLE
Save and load a set of 'favorite' coordinate output formats

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#448]
Enable one person to set up a group of coordinate formats used by a specific group of people/for a specific task and save that out (as "favorites" if you will) that other people doing the same job, using the same SOP would be able to load, instead of having to manually set up their machine to have the required formats (and risking having variations from the original).

**Comment by dfoll** [comment]
This is functioning as requested in ArcMap and ArcGIS Pro.

**Comment by BobBooth** [comment]
There is a problem with the import coordinate format functionality where, if you import a file of coordinate output settings, it **adds** the coordinates to the **existing set** of output coordinates.  This allows non-unique names to exist in the output coordinate table (something that the addin prevents if you attempt to do it via the UI).
![image](https://user-images.githubusercontent.com/3801392/54298299-dd2e9180-458e-11e9-98db-0b3308be8577.png)

This leads to another problem, where if you have imported a set of output coordinates once or twice and you export your coordinates to a feature class, ArcMap will **crash**.

Also, if you open a new map in ArcMap and the addin pane is in this state, when you try to collect new locations, it prompts for a basemap layer, even if there is one on the map.
![image](https://user-images.githubusercontent.com/3801392/54298698-a311bf80-458f-11e9-93c3-2734eaac1fac.png)

**Comment by dfoll** [comment]
@saip has noted this and will see about a fix

**Comment by dfoll** [comment]
@saip @BobBooth just brought an interesting thought to me... would it be possible that whenever you load a set of favorite Outputs, it just removes and replaces whatever is there? This is probably the simplest way to handle the problem

**Comment by dfoll** [comment]
The intended behavior for this is if you have one list, then import a second list that contains the same Output fields, the fields that have matching names will overwrite the existing field of the same name so that there will not be duplicate/non-unique names in the list. In the case that those fields that had the same name actually had different formatting, the formatting from the second list will be brought in.

Testing with DefenseSolutions\CoordinateConversion\Testing\CTLocalGovTeam-dev\63 this looks good for 
- [ ] ArcGIS Pro
- [ ] ArcMap

**Comment by BobBooth** [comment]
Doc changes visible in What's new, CC, and MT Release page on STG.
