### ISSUE TITLE
Coordinate Conversion input coordinate -- formatting lost in Northern Hemisphere

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#527]
I added -- as a separator between the Lat Long values in a DD output. This output displayed in the List when I clicked in the Southern Hemisphere, but no dashes were returned when I clicked in the Northern Hemisphere.
![image](https://user-images.githubusercontent.com/3801392/47811974-7ca86180-dd1d-11e8-881a-3fa672853ce6.png)

The problem affects + and - symbols used as separators, as they also have significance in indicating hemisphere. 
The problem does not affect other special characters, such as !,@,#,$,%,^,&,*,(,),=,<,>,?,/,\,|,,.,

ArcGIS Pro 2.3.0 beta 1 build 14476
Coordinate Conversion 4.1.1.19 (latest October build)

**Comment by dfoll** [comment]
I would like to have this one worked on, but I think our team needs to research a little more first. Just thinking out loud without verifying the issue myself, I'm wondering if the example we give is confusing because `-` has a special meaning  when it comes to coordinates. 
- Do we get the same behavior using `$$` or is this unique to `--`? 

Definitely need to fix this, just think we could clean up this issue a little bit first

**Comment by BobBooth** [comment]
@dfoll - good point. I will look at this again.

**Comment by dfoll** [comment]
@saip in the comment above, @BobBooth believes this problem is occuring because the minus sign is a special character. Knowing that, are we able to move ahead with fixing this issue?

**Comment by dfoll** [comment]
spoke with @saip about this. I think we need to understand exactly how we need the parser to fix this issue. How do we get the code to understand `-` used as a delimiter, versus being used as a hemisphere designation? 

For example, if the coordinate 54.72--48.37 is provided, how do we parse out if that is `54.72N-48.37W" or `54.72N--48.37E` from just what is provided textually.

**Comment by BobBooth** [comment]
So, we should detect+ and - symbols used as delimeters and warn the users that they are interpreted as hemisphere indicators only, cannot be also used as delimiters. Then not allow that input.
![image](https://user-images.githubusercontent.com/3801392/56299982-12d11800-6103-11e9-8f03-73465c73a3ea.png)

**Comment by dfoll** [comment]
@saip please check out @BobBooth [comment](https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/527#issuecomment-484137143) on how we want the interaction to be.

- if the user tries to enter a `+` or `-` when creating custom formatting for DD/DDM/DMS, the input box should highlight red, with a tooltip style message that tells the user "+ and - are significant characters for latitude/longitude and cannot be used in custom formatting"

**Comment by dfoll** [comment]
#600  was created to wrap up this workflow. Without #600 the user will be unable to "mark" something as being in the Southern or Western hemisphere

**Comment by dfoll** [comment]
Tested with build 94 of CC. With this build +/- can no longer be used as characters when providing custom formatt
![image](https://user-images.githubusercontent.com/5322669/58205795-2c322a80-7c94-11e9-94cf-63718a0176f0.png)
ing

**Comment by dfoll** [comment]
The logic that was used to issue this was to disallow "+/-" characters  when entering custom formatting. This broke the fix that was put in for #468 in the PR #518. To resolve this regression issue we need to improve the logic that was used. 

- Instead of absolutely disallowing "+/-", those characters should only be allowed within a latitude or longitude coordinate.
- "+/-" are still allowed when embedded in a latitude or longitude coordinate.
   - Example: "DD-MM-SS.SS DD-MM-SS.SS" is a valid coordinate formatting _"-" is within the coordinate_
   - Example: "DD-MM-SS.SS-DD-MM-SS.SS" is not a valid coordinate pair _"-" is in front of/not within the coordinate_
   - Example: "-DD-MM-SS.SS DD-MM-SS.SS" is not a valid coordinate pair _"-" is in front of/not within the coordinate_
   - Example: "DD-MM-SS.SS+DD-MM-SS.SS" is not a valid coordinate pair _"-" is in front of/not within the coordinate_


<font size="10" color="red">This is some text!</font>

**Comment by saip** [comment]
@dfoll Please confirm if below mentioned are valid/invalid coordinate formatting
- *-*DD-MM-SS.SS DD-MM-SS.SS
- DD-MM-SS.SS*+*DD-MM-SS.SS **

**Comment by dfoll** [comment]
@saip 

`*-*DD-MM-SS.SS DD-MM-SS.SS`  is not a valid coordinate pair because there is a "-" in front of the latitude [assuming this is a lat/lon pair, but lon/lat would not change anything, i only used the word to refer to the position]

`DD-MM-SS.SS*+*DD-MM-SS.SS **`  is not a valid coordinate pair because there is a "+" in front of the longitude [assuming this is a lat/lon pair, but lon/lat would not change anything, i only used the word to refer to the position]

`

**Comment by dfoll** [comment]
When creating custom formatting "+/-" are treated a special characters and cannot be placed by the user in front of either latitude or longitude. This prevents confusion in a case where a "-" has been inserted in front of a "-" that indicates S or W hemisphere. 

If a user wants a "-" to display to indicate S or W hemisphere, they will use the "Show - for S/W hemisphere" checkbox

**Comment by dfoll** [comment]
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/june-2019-coordinate-conversion.htm
- \\...\CoordinateConversion\Dev\148\
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
-\\...\DefenseSolutions\MilitaryToolsforArcGIS\Dev\314\

**Comment by lfunkhouser** [comment]
Verified in MT 314 and CC 148 and solutionsdev - not on STG yet.
