### ISSUE TITLE
Changing the input display coordinate type causes the add-in to register coordinates as invalid

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#551]
## Background
Changing the Display Coordinates to something other than MGRS is causing Coordinate Conversion to think that MGRS coordinates are invalid.

ArcGIS Pro 2.3.0.15723 MT 176
Was not able to reproduce with ArcMap 10.3.1 MT 176

## Repro steps
1. In the Coordinate Conversion pane paste in `42S XD 45583 55343`
2. Press Enter
_coordinates are located_
3. Click the `Edit Properties` button
4. Change the Display Coordinate to DD
5. Click Clear All
6. Paste in `42S XD 45583 55343` or `42SXD4558355343`
7 Press Enter
_Invalid Coordinate message is displayed_
_**follow-on steps**_
8. Paste in `34.82997N 70.592043E`
9. Press Enter
_coordinates are located_
10. Paste in `42S XD 45583 55343` or `42SXD4558355343`
11. Press Enter
_Invalid Coordinate message is displayed_
12. Click the `Edit Properties` button
13. Change the Display Coordinate to MGRS
14. Paste in `42S XD 45583 55343`
15. Press Enter
_coordinates are located_
16. Change the Display Coordinate to DMS
17. Paste in `42S XD 45583 55343` or `42SXD4558355343`
18. Press Enter
_Invalid Coordinate message is displayed_

### Could not get the same behavior from other coordinate types
1. Change the Display Coordinate to MGRS
2. Paste in `42S XD 45583 55343`
3. Press Enter
_coordinate is located_
4. Paste in `34.82997N 70.592043E`
5. Press Enter
_coordinate is located_
6. Change the Display Coordinate to DD 
7. Paste in `34 49 47.89N 070 35 31.35E`
_coordinate is located_
8. Change the Display Coordinate to DMS
9. Paste in `34.82997N 70.592043E` 
_coordinate is located_
10. Paste in `42S XD 45583 55343` 
11. Press Enter
_Invalid Coordinate message is displayed_

**Comment by dfoll** [comment]
@lfunkhouser

**Comment by kgonzago** [comment]
After more testing, this issue happens with all MGRS and USNG coordinates. And it also happens to not only in DD but DMS, DDM, and UTM. A bit more of a larger issue than expected. The logic leading up to this [line](https://github.com/Esri/coordinate-conversion-addin-dotnet/blob/dev/source/CoordinateConversion/CoordinateConversionLibrary/Models/CoordinateMGRS.cs#L227) will need to be refactored a bit since in this issue the context is a user is pasting MGRS coordinates in the input textbox with DD as the output format in the list component. The MGRS formatter needs to properly handle parsing into DD/DDM/DMS/UTM notations

**Comment by kgonzago** [comment]
Fix for this issue is in this [PR](https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/554)

**Comment by csmoore** [comment]
Dev build created for QC at: `Solutions\DefenseSolutions\CoordinateConversion\January2019\Dev\46`

**Comment by BobBooth** [comment]
@lfunkhouser  - This was a newly-discovered issue on relatively new functionality. It is not listed as a Known Issue, so I'm not sure if it needs to be mentioned in Issues Addressed.  I think we can remove the doc tags and close.
