### ISSUE TITLE
Coordinate conversion does not handle out of bounds clicks like DD in Pro

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#583]
If you are adding coordinates interactively by clicking, and you click outside of the map extent, a point is added.  Should handle this the way we do with DD, pop up a "Point is out of bounds" message.
See: https://github.com/Esri/distance-direction-addin-dotnet/issues/634
Currently the addin lets you zoom out and clicks out of bounds, which causes an ugly exception message to popup when you export the points to feature class.
![image](https://user-images.githubusercontent.com/3801392/54305480-c17eb780-459d-11e9-9874-5716d3895a65.png)

This does not happen in ArcMap (10.3.1) with the released (2.4.0.25) CC addin.

Pro 2.3  Coordinate Conversion 4.2.0.25 (Released)

**Comment by dfoll** [comment]
Testing with ...\Solutions\DefenseSolutions\CoordinateConversion\Testing\CTLocalGovTeam-dev\89 
#### ArcGIS Pro 2.2
1. Click a point out of bounds. 
2. "Point is out of bounds" warning message is displayed. No point is placed.
#### ArcMap 10.3.1
1. Click a point out of bounds. 
2. "Point is out of bounds" warning message is displayed. No point is placed.

### Doc updates can be found here:
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/june-2019-coordinate-conversion.htm
-  ...\Solutions\DefenseSolutions\CoordinateConversion\Testing\CTLocalGovTeam-dev\90
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- Commercial\Solutions\DefenseSolutions\MilitaryToolsForArcGIS\Dev\266
- https://solutionsdev.arcgis.com/defense/what-is-new/

NOTE: Changes to the What's New page and CC homepage were done in [this PR](https://github.com/ArcGIS/arcgis-solutions-website/pull/7775) they will be available after the 1500 (pdt) build happens
NOTE: the code in the MT build will not match the doc. The reason for this is the code in the CC repo has not been merged to the dev branch, the build script for MT calls the dev branch of CC. The link to the MT .zip is provided only so that we can confirm that pdf is updated. If you want to check the code against the documentation you should use the CC .zip file

**Comment by dfoll** [comment]
TODO:
- [ ] check the doc -- and remove G- QC (Doc) label
- [ ] add correct closing labels to issue (then move to Done column)

**Comment by lfunkhouser** [comment]
Update required for Jenkins/build to build to folder ArcMap 10.4.1 - 10.7.1

### CC home page
Requirements: Update Software ArcMap 10.4.1 - 10.7.1
What you get: Update Folder for ArcMap to 10.4.1 - 10.7.1
What's new: June 2019: Update to include Support for ArcGIS Pro 2.4, ArcMap 10.7 - 10.7.1

### CC Release notes
Update version supported to ArcMap 10.4.1 - 10.7.1

### MT Release notes
Update version supported to ArcMap 10.4.1 - 10.7.1
Update version supported to ArcGIS Pro 2.2 - 2.4

### What's New
Under Military tools for ArcGIS
Support for ArcGIS Pro 2.4
Support for ArcMap 10.7 - 10.71

Under Coordinate Conversion
Support for ArcMap 10.7 - 10.7.1

**Comment by dfoll** [comment]
- GitHub changes in this [PR](https://github.com/ArcGIS/arcgis-solutions-website/pull/7788)
