### ISSUE TITLE
View Details window should be resizable

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#590]
### Background
Resizing the View details window is not intuitive. It can be done by changing the width of the field headings, but this is not the typical way that a user expects to be able to resize a window.

- This is for both ArcMap and ArcGIS Pro.

### Current behavior
The only way to change the size of a View Details window in ArcMap or ArcGIS Pro is to change the width of the fields. 
![image](https://user-images.githubusercontent.com/5322669/54535307-a11b7800-4964-11e9-9524-f7e99034db59.png)
_Note in the screenshot you get resize handles when you hover over the field edges but not the corners of the window as users expect._

### Expected behavior
You should be able to resize a window by hovering over a corner and getting the typical resize handles.
![image](https://user-images.githubusercontent.com/5322669/54535509-0f603a80-4965-11e9-9f7f-eebe2f450661.png)
_Typical way that resize handles are displayed in ArcGIS_
You should still also be able to resize fields within the window the standard way that ArcGIS resizes fields, however this should not change the window size.
![image](https://user-images.githubusercontent.com/5322669/54535870-dffdfd80-4965-11e9-8ac9-75f7034bd70f.png)
_Resizing a field in ArcGIS_

**Comment by dfoll** [comment]
Issues #590,#591, #592 are all very closely related, but have their own specific differences that make them unique. They very likely will be handled all in the same effort, but all require their own very specific fixes.

**Comment by csmoore** [comment]
Testing from latest `Development\Commercial\Solutions\DefenseSolutions\CoordinateConversion\Testing\CTLocalGovTeam-dev\91\`

Pro behavior looks good and was tested with https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/591#issuecomment-492804547 

Not sure if it is just me, but I'm having a problem launching the addin in ArcMap (it is crashing for me) so looking into the cause. Not sure if @dfoll or @saip have seen this issue.

![image](https://user-images.githubusercontent.com/3090809/57808907-736b6900-7732-11e9-9da0-063e5cd36838.png)

**Comment by csmoore** [comment]
Tested in ArcMap, resize/fill now works as expected, however there are a few minor issues with this (in ArcMap only):

1. The default size of the form seems to be much larger than necessary
2. The form opens with a horizontal scroll bar even though there is nothing to scroll (this scroll bar disappears if the window is resized). Note this scroll bar seems to be related to an extra column in the grid control.
3. The form is set to "Always on Top" (this may be by design) 

I would recommend addressing 1, 2 above ( @saip @dfoll ) 
 
Large default size and scroll bars:
![image](https://user-images.githubusercontent.com/3090809/57867273-d579ac00-77ce-11e9-9b12-c80b4b02ae2b.png)

Extra column in the grid control:
![image](https://user-images.githubusercontent.com/3090809/57868479-107cdf00-77d1-11e9-9acd-599f503c12fa.png)

**Comment by saip** [comment]
@dfoll @csmoore https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/590#issuecomment-493126056 is resolved along with https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/586#issuecomment-493881267

**Comment by csmoore** [comment]
Verified issues with large size and scrollbars in ArcMap are resolved.

![image](https://user-images.githubusercontent.com/3090809/58052919-16055c80-7b24-11e9-8811-3a42a26d9db4.png)

**Comment by dfoll** [comment]
### Doc updates:
- ...\Solutions\DefenseSolutions\CoordinateConversion\Testing\csm-build-brokey-broke-on-10-4-1\104
- _MT build is currently broken, so no pdf there_
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/june-2019-coordinate-conversion.htm
