### ISSUE TITLE
Display/Capture Live Coordinates Disables When Tool is Changed in ArcMap

### ISSUE THREAD

**Issue by mcalamito** [Esri/coordinate-conversion-addin-dotnet#94]
Currently, live coordinates are only captured and displayed when the Coordinate Conversion Addin is in focus and the Map Point Tool has been enabled. The user hover the mouse over the Data Frame and populate coordinates. As soon as another tool (select elements, information tool, selection tool, etc.) is enabled, coordinate capture ceases. Is there anyway to keep this going in the background until the user proactively disables the Map Point Tool to lock into a specific coordinate?

**Comment by topowright** [comment]
More feedback on this same issue was captured from @cswinehart today. 

When users has selected the Map Point Tool they only get to click one time on the map to collect the coordinate. They would like for the add-in to have the ability to continue to grab coordinates, instead of having to re select the Map Point Tool each time they want to grab a new coordinate. The user experience would be something like this: 

User selects the Map Point Tool
User sees coordinates update as the cursor moves over the map. 
User selects first coordinate by clicking on the map
Coordinate locks in the add-in (up to this point is the way we currently have the experience set up)
User selects another location by clicking on the map and the coordinate updates in the add-in
This step is repeated as many times as necessary
**Bonus: A user can click five times in the map and all five coordinates are captured in some sort of batch grab.

**Comment by mcalamito** [comment]
@cswinehart @topowright agree completely with the above assessment as well.

**Comment by BobBooth** [comment]
Saw this today in Holistic - seems strange that the Map Point Tool loses focus after a single click on the map. What if I clicked the wrong place?

**Comment by dfoll** [comment]
@lfunkhouser @nfeuerstein I'm closing this. Coordinate Conversion currently maintains focus and allows for the collection of multiple points until the user makes a deliberate decision to enable another tool.
